# coding=utf-8
"""Reads what slicers leave inside a G-code file: settings, estimates and thumbnails.

Only the start and the end of the file are read (slicers put their summary in one of the two),
so this stays quick even for a 100 MB file on a Raspberry Pi.

Understands the comment styles of PrusaSlicer / SuperSlicer / OrcaSlicer / Bambu Studio,
Cura, Simplify3D and KISSlicer. Anything unrecognised is simply left out.
"""
from __future__ import absolute_import

import base64
import binascii
import os
import re

HEAD_BYTES = 1024 * 1024      # thumbnails can be big, and OrcaSlicer/Prusa put them up front
TAIL_BYTES = 256 * 1024       # PrusaSlicer's settings block sits at the very end

_KV = re.compile(r"^;\s*([A-Za-z_][\w \[\]\(\)/%\-\.]*?)\s*[=:]\s*(.+?)\s*$")
_THUMB_BEGIN = re.compile(r"^;\s*thumbnail(?:_(JPG|PNG|QOI))?\s+begin\s+(\d+)x(\d+)\s+(\d+)", re.I)
_THUMB_END = re.compile(r"^;\s*thumbnail(?:_(?:JPG|PNG|QOI))?\s+end", re.I)


def read_ends(path, head=HEAD_BYTES, tail=TAIL_BYTES):
    """Return (head_text, tail_text, size). tail_text is '' when the file is small enough
    that the head already covers everything."""
    size = os.path.getsize(path)
    with open(path, "rb") as fh:
        head_bytes = fh.read(head)
        tail_bytes = b""
        if size > head:
            fh.seek(max(head, size - tail))
            tail_bytes = fh.read(tail)
    return (
        head_bytes.decode("utf-8", "replace"),
        tail_bytes.decode("utf-8", "replace"),
        size,
    )


def parse_duration(text):
    """'1h 41m 12s', '2d 3h', '6072', '1:41:12' -> seconds (float) or None."""
    if text is None:
        return None
    s = str(text).strip().strip('"')
    if re.match(r"^\d+(\.\d+)?$", s):
        return float(s)
    total, hit = 0.0, False
    for num, unit in re.findall(r"(\d+(?:\.\d+)?)\s*([dhms])\b", s, re.I):
        hit = True
        total += float(num) * {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit.lower()]
    if hit:
        return total
    m = re.match(r"^(\d+):(\d{1,2}):(\d{1,2})$", s)
    if m:
        return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3))
    return None


def _first_number(value):
    """'5320.12, 0.0' -> 5320.12 ; '15.9g' -> 15.9"""
    if value is None:
        return None
    m = re.search(r"-?\d+(?:\.\d+)?", str(value))
    return float(m.group(0)) if m else None


def _sum_numbers(value):
    """'5320.12, 812.5' (multi extruder) -> 6132.62"""
    if value is None:
        return None
    nums = re.findall(r"-?\d+(?:\.\d+)?", str(value))
    return sum(float(n) for n in nums) if nums else None


def _kv_pairs(text):
    out = {}
    for line in text.splitlines():
        if not line.startswith(";"):
            continue
        m = _KV.match(line)
        if m:
            key = m.group(1).strip().lower()
            out.setdefault(key, m.group(2).strip())
    return out


def find_thumbnails(head_text):
    """Yield dicts {width, height, format, data: bytes} for each embedded thumbnail."""
    lines = head_text.splitlines()
    i = 0
    n = len(lines)
    while i < n:
        m = _THUMB_BEGIN.match(lines[i])
        if not m:
            i += 1
            continue
        fmt = (m.group(1) or "PNG").upper()
        width, height = int(m.group(2)), int(m.group(3))
        chunks = []
        i += 1
        while i < n and not _THUMB_END.match(lines[i]):
            chunk = lines[i].lstrip(";").strip()
            chunks.append(chunk)
            i += 1
        try:
            data = base64.b64decode("".join(chunks), validate=False)
        except (binascii.Error, ValueError):
            data = b""
        if data:
            if data[:8] == b"\x89PNG\r\n\x1a\n":
                fmt = "PNG"
            elif data[:3] == b"\xff\xd8\xff":
                fmt = "JPG"
            yield {"width": width, "height": height, "format": fmt, "data": data}
        i += 1


def best_thumbnail(head_text, prefer_width=None):
    """Largest usable thumbnail (PNG/JPG), or the one closest to prefer_width if given."""
    thumbs = [t for t in find_thumbnails(head_text) if t["format"] in ("PNG", "JPG")]
    if not thumbs:
        return None
    if prefer_width:
        return min(thumbs, key=lambda t: abs(t["width"] - prefer_width))
    return max(thumbs, key=lambda t: t["width"] * t["height"])


def _detect_slicer(head_text):
    for line in head_text.splitlines()[:400]:
        low = line.lower()
        if low.startswith("; generated by "):
            return line[len("; generated by "):].strip().split(" on ")[0]
        if low.startswith(";generated with "):
            return line[len(";generated with "):].strip()
        if low.startswith("; g-code generated by "):
            return line[len("; g-code generated by "):].strip()
        if low.startswith("; bambustudio") or low.startswith("; orcaslicer") or low.startswith("; superslicer"):
            return line.lstrip("; ").strip()
        if "simplify3d" in low and low.startswith(";"):
            return "Simplify3D " + line.split("Simplify3D")[-1].strip(" ()")
        if low.startswith("; kisslicer") or low.startswith("; ***"):
            if "kiss" in low:
                return "KISSlicer"
    return None


def summarise(path):
    """Everything worth showing about a file, as plain JSON-able data."""
    head, tail, size = read_ends(path)
    kv = _kv_pairs(head)
    for k, v in _kv_pairs(tail).items():
        kv[k] = v          # the settings footer wins over anything in the header

    info = {"size": size, "slicer": _detect_slicer(head)}

    # ~~ time ~~
    t = None
    for key in ("estimated printing time (normal mode)", "total estimated time", "estimated printing time", "print time"):
        if key in kv:
            t = parse_duration(kv[key])
            if t:
                break
    if t is None:
        m = re.search(r"^;\s*TIME:\s*(\d+)", head, re.M)          # Cura
        if m:
            t = float(m.group(1))
    if t is None:
        m = re.search(r"^;\s*Build time:\s*(.+)$", head, re.M)      # Simplify3D
        if m:
            t = parse_duration(m.group(1))
    info["estimatedSeconds"] = t

    # ~~ filament ~~
    mm = _sum_numbers(kv.get("filament used [mm]"))
    g = _sum_numbers(kv.get("filament used [g]") or kv.get("total filament weight [g]") or kv.get("filament weight"))
    cm3 = _sum_numbers(kv.get("filament used [cm3]") or kv.get("filament used [cm^3]"))
    if mm is None:
        m = re.search(r"^;\s*Filament used:\s*([\d.]+)\s*m\b", head, re.M | re.I)     # Cura
        if m:
            mm = float(m.group(1)) * 1000.0
    info["filamentMm"] = mm
    info["filamentGrams"] = g
    info["filamentCm3"] = cm3
    cost = _first_number(kv.get("total filament cost") or kv.get("filament cost"))
    info["cost"] = cost

    # ~~ settings that matter to an operator ~~
    def num(*keys):
        for k in keys:
            if k in kv:
                v = _first_number(kv[k])
                if v is not None:
                    return v
        return None

    def txt(*keys):
        for k in keys:
            if k in kv:
                return kv[k].strip('"')
        return None

    info["layerHeight"] = num("layer_height", "layer height")
    info["firstLayerHeight"] = num("first_layer_height", "initial_layer_print_height", "layer_height_0")
    info["nozzleDiameter"] = num("nozzle_diameter")
    info["nozzleTemp"] = num("temperature", "nozzle_temperature", "first_layer_temperature", "print temperature")
    info["bedTemp"] = num("bed_temperature", "hot_plate_temp", "first_layer_bed_temperature", "textured_plate_temp")
    info["chamberTemp"] = num("chamber_temperature")
    info["filamentType"] = txt("filament_type")
    info["filamentName"] = txt("filament_settings_id", "filament_name")
    info["filamentColor"] = txt("filament_colour", "extruder_colour")
    info["infill"] = txt("fill_density", "sparse_infill_density", "infill density")
    info["supports"] = txt("support_material", "enable_support")
    info["printerModel"] = txt("printer_model", "printer_settings_id")
    layer_count = num("total layer number", "layer_count", "total layers")
    if layer_count is None:
        m = re.search(r"^;\s*LAYER_COUNT:\s*(\d+)", head, re.M)
        if m:
            layer_count = float(m.group(1))
    info["layerCount"] = int(layer_count) if layer_count else None

    # Cura writes the model bounds as ;MINX:... ;MAXX:...
    bounds = {}
    for axis in ("X", "Y", "Z"):
        lo = re.search(r"^;\s*MIN%s:\s*(-?[\d.]+)" % axis, head, re.M)
        hi = re.search(r"^;\s*MAX%s:\s*(-?[\d.]+)" % axis, head, re.M)
        if lo and hi:
            bounds[axis.lower()] = [float(lo.group(1)), float(hi.group(1))]
    if len(bounds) == 3:
        info["bounds"] = bounds

    thumbs = [
        {"width": t["width"], "height": t["height"], "format": t["format"]}
        for t in find_thumbnails(head)
        if t["format"] in ("PNG", "JPG")
    ]
    info["thumbnails"] = thumbs
    # drop empty values so the JSON stays small and the front end can test for presence
    return {k: v for k, v in info.items() if v not in (None, "", [])}
